### PR TITLE
Add support for auto-generated trigger function

### LINKED ISSUE #209: Replace boilerplate function definition with dedicated source generator
With .NET 5 [source generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/) it should be possible to remove boilerplate code that invokes [NServiceBus endpoint](https://docs.particular.net/nservicebus/hosting/azure-functions/service-bus#basic-usage-azure-function-definition) from Azure Function method body:

``` csharp
 [FunctionName("MyFunctionsEndpoint")]
    public async Task Run(
        [ServiceBusTrigger(queueName: "MyFunctionsEndpoint")]
        Message message,
        ILogger logger,
        ExecutionContext executionContext)
    {
        await endpoint.Process(message, executionContext, logger);
    }
```

### PR DESCRIPTION
**Pull request by SeanFeldman**
Closes #209 

Add support for auto-generated trigger function to remove boilerplate code

### CODE REVIEW

**Review by bording — APPROVED** [review]

**Comment by udidahan** [comment]
Will there be some documentation/samples created for this as well?

**Comment by SeanFeldman** [comment]
What do you think @udidahan? 🙂

**Comment by udidahan** [comment]
Well, I hope so, but seeing that the linked issue was closed, and there was no other place that indicated that those things would be included, so I raised the question.

**Comment by SeanFeldman** [comment]
When a GitHub PR is closed with a reference to the original issue (`'Closes #209'`), the issue is automatically closed as well.
The issue isn't fully completed and is technically still a work in progress until the rest of the work associated with a release is completed. Completion requires assigning a release (1.1.0), a label (`Improvement` or `Feature` in this case), creating and reviewing an announcement, and updating both the documentation and sample(s). When a release is officially made (promoted to NuGet), it's publicly [announced](https://discuss.particular.net/c/announcements/5). Hope that helps to clear any question.

**Comment by SeanFeldman** [comment]
@udidahan, you can review https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/issues/209 to see the full list of actions that took place. Cheers!

**Pull request merged**
